config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  resources :publications, except: :show
  resources :monetary_accounts, except: :show
  put '/toggle_profile', to: 'profiles#toggle_profile'
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appreciation.rb
class Appreciation < ApplicationRecord
  belongs_to :user
  enum appreciation_kind: { hug: 0, coffee: 1 }
end

app/models/monetary_account.rb
class MonetaryAccount < ApplicationRecord
  belongs_to :user
end

app/models/multiplier.rb
class Multiplier < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
  has_many :multipliers
  has_many :publications
  accepts_nested_attributes_for :multipliers
  validates :user, presence: true
  validates :fullname, :occupation, :biography, :coffee_price, :currency_sign, presence: true
  validates_length_of :multipliers, maximum: 4
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :profile
  has_one_attached :image
  validates :profile, presence: true
  validates :subtitle, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  has_many :monetary_accounts
  has_many :appreciations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    #falta notificacion
    #de que esa pagina no existe
    redirect_to(root_url)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/monetary_accounts_controller.rb
class MonetaryAccountsController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.profile.present?
      @profile = current_user.profile
      @monetary_accounts = current_user.monetary_accounts.all 
    else
      redirect_to root_url
    end
  end

  def new
    if current_user.profile.present? 
      @profile = current_user.profile
      @monetary_account = MonetaryAccount.new
    else
      redirect_to root_url
    end
  end

  def create
    @monetary_account = current_user.monetary_accounts.build(monetary_account_params)
    if @monetary_account.save
      redirect_to root_url, notice: "La cuenta ha sido creada"
    else
      flash.now[:alert] = "No se pudo crear la cuenta"
      render 'new'
    end
  end

  def edit
    if current_user.monetary_accounts.find(params[:id]).present?
      @profile = current_user.profile
      @monetary_account = current_user.monetary_accounts.find(params[:id])
    else 
      redirect_to root_url
    end
  end

  def update
    @monetary_account = current_user.monetary_accounts.find(params[:id])
    if @monetary_account.update(monetary_account_params)
      redirect_to monetary_accounts_url, notice: "Cuenta actualizada"
    else
      flash.now[:alert] = "No se pudo actualizar la cuenta"
      render 'edit'
    end
  end

  def destroy
    @monetary_account = MonetaryAccount.find(params[:id])
    if @monetary_account.destroy
      redirect_to monetary_accounts_url, notice: "La cuenta ha sido eliminada"
    else
      flash.now[:alert] = "No se pudo eliminar la cuenta"
      render 'edit'
    end
  end

  private

  def monetary_account_params
    params.require(:monetary_account).permit(:entity, :account_email, :identification, :account_kind, :account_number)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :toggle_profile]
  before_action :is_published,       only: :show
  
  def new
    if current_user.profile.present?
      redirect_to root_url, notice: "Ya existe el perfil"
    else     
      @profile = Profile.new
      count =0
      3.times do |time|
        count += 1
        @profile.multipliers.build(quantity: count)
      end
      @profile.multipliers.build(quantity: 5)
    end
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to root_url, notice: "El perfil ha sido creado"
    else
      flash.now[:alert] = "No se pudo crear el perfil"
      render 'new'
    end
  end

  def show
    if current_user.profile.present? 
      @profile = current_user.profile
      @publications = current_user.profile.publications.all
    end
  end
  
  def edit
    if current_user.profile.present?
      @profile = current_user.profile
    else
      redirect_to new_profile_url 
    end
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      if @profile.is_published
        redirect_to profile_url, notice: "El perfil ha sido actualizado"
      else 
        redirect_to edit_profile_url, notice: "El perfil ha sido actualizado"
      end
    else
      flash.now[:alert] = "No se pudo actualizar el perfil"
      render 'edit'
    end
  end

  def toggle_profile
    @profile = Profile.find(params[:id])
    result = @profile.update(is_published: params[:is_published])
    render json: { profile: @profile, result: result }
  end

  private

  def profile_params
    params.require(:profile).permit(:fullname, :occupation, :biography, :coffee_price, :currency_sign, :avatar, multipliers_attributes: [:id, :quantity])
  end

  def is_published
    @profile = Profile.find(params[:id])
    redirect_to(root_url) unless @profile.is_published
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.profile.present? 
      @profile = current_user.profile
      @publications = current_user.profile.publications.all
    else 
      redirect_to root_url
    end
  end

  def new
    if current_user.profile.present? 
      @profile = current_user.profile
      @publication = Publication.new
    else
      redirect_to root_url
    end
  end

  def create
    @publication = current_user.profile.publications.build(publication_params)
    if @publication.save
      redirect_to publications_url, notice: "La publicación ha sido creada"
    else
      flash.now[:alert] = "No se pudo crear la publicación"
      render 'new'
    end
  end

  def edit
    if current_user.profile.publications.find(params[:id]).present?
      @profile = current_user.profile
      @publication = @profile.publications.find(params[:id])
    else 
      redirect_to root_url
    end
  end

  def update
    @publication = current_user.profile.publications.find(params[:id])
    if @publication.update(publication_params)
      redirect_to publications_url, notice: "La publicación ha sido actualizada"
    else
      flash.now[:alert] = "No se pudo actualizar la publicación"
      render 'edit'
    end
  end

  def destroy
    @publication = Publication.find(params[:id])
    if @publication.destroy
      redirect_to publications_url, notice: "La publicación ha sido eliminada"
    else 
      flash.now[:alert] = "No se pudo eliminar la publicación"
      render 'edit'
    end
  end

  private

  def publication_params
    params.require(:publication).permit(:subtitle, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<%= render 'layouts/main_header' %>
<div class="home-one-container">
  <% flash.each do |message_type, msg| %>
    <%= content_tag(:div, id: "msg-wrapper", class: "msg-wrapper #{message_type}") do %>
      <%= content_tag(:div, class: "vectormsg-wrapper") do %>
        <%= image_tag("Vectormsg.svg", id: "vectormsgwrapper-img") %>                
      <% end %>
      <%= content_tag(:h6, msg, class: "primary-font") %>
    <% end %>
  <% end %>
  <div class="coffees-img-wrapper">
    <%= image_tag("coffees.svg", class: "coffees-img") %>
  </div>
  <div class="intro-text-wrapper">
    <h1 class="intro-text-thick second-font ">Un café es un abrazo atrapado en una taza</h1>
  </div>
  <div class="intro-text-thin primary-font" >
    <h2>Recibe aprecio y gratitud mediante donaciones online</h2>
  </div>
  <div class="create-profile-link-wrapper">
    <% if !current_user %>
      <%= link_to new_user_registration_path, class: "create-profile-link second-bkgrnd" do %>
        <h2 class="create-profile-link-text primary-font">Crear mi perfil</h2>
      <% end %>
    <% else %>
      <% if current_user.profile %>
        <%= link_to edit_profile_path(id: current_user.profile.id), class: "create-profile-link second-bkgrnd" do %>
          <h2 class="create-profile-link-text primary-font">Editar mi perfil</h2>
        <% end %>
      <% else %>
        <%= link_to new_profile_path, class: "create-profile-link second-bkgrnd" do %>
          <h2 class="create-profile-link-text primary-font">Crear mi perfil</h2>
        <% end %>
      <% end %>  
    <% end %>
  </div>
</div>
<div class="home-two-container second-bkgrnd">
  <div class="intro-text-container">
    <h1 class="intro-text-thick-2 second-font ">Un perfil dedicado a recibir agradecimientos</h1>
  </div>
  <div class="intro-text-last primary-font">
    <h2>Puedes crear una página en minutos sin conocimientos técnicos. Muestra tus datos y agradecimientos recibidos de otras personas.</h2>
  </div>
  <div class="cellphones-img-wrapper">
    <%= image_tag("cellphones.svg", class: "cellphones-img") %>
  </div>
</div>

app/views/layouts/_admin-menu-desktop.html.erb
<div class="admin-menu-desktop">
  <div>
    <%= link_to edit_profile_path(id: @profile.id), class: "admin-menu-link" do %>
      <% if controller.controller_name == "profiles"%>
        <%= image_tag("profile-icon-red.svg") %>
      <% else %>
        <%= image_tag("profile-icon.svg") %>        
      <% end %>
      <%= content_tag :h2, "Perfil", class: (controller.controller_name == "profiles" ? "admin-text-red" : "admin-text-black")%>
    <% end %>
  </div>
  <div>
    <%= link_to publications_path, class: "admin-menu-link" do %>
      <% if controller.controller_name == "publications"%>
        <%= image_tag("imagenes-icon-red.svg") %>
      <% else %>
        <%= image_tag("imagenes-icon.svg") %>        
      <% end %>
      <%= content_tag :h2, "Imágenes", class: (controller.controller_name == "publications" ? "admin-text-red" : "admin-text-black")%>    
    <% end %>
  </div>
  <div>
    <%= link_to monetary_accounts_path, class: "admin-menu-link" do %>
      <% if controller.controller_name == "monetary_accounts"%>
        <%= image_tag("cuentas-icon-red.svg") %>
      <% else %>
        <%= image_tag("cuentas-icon.svg") %>        
      <% end %>
      <%= content_tag :h2, "Cuentas", class: (controller.controller_name == "monetary_accounts" ? "admin-text-red" : "admin-text-black")%>    
    <% end %>
  </div>
</div>

app/views/layouts/_admin_header.html.erb
<header class="header third-bkgrnd">
  <div class="admin-header second-bkgrnd">
    <div>
      <% unless current_page?(new_profile_path) %>
        <div id="menu-icon">
          <div class="menu-icon-line"></div>
          <div class="menu-icon-line"></div>
          <div class="menu-icon-line"></div>
        </div>
      <% end %>
    </div>
    <%= link_to root_path, class: "big-logo-font second-font" do %>
      <h1>A&C</h1>
    <% end %>
  </div>
  <% unless current_page?(new_profile_path) %>
    <div class="signout-dropdown">
      <div class="signout-dropbtn">
        <% if @profile.avatar.present? %>
          <div class="profile-avatar"><%= image_tag @profile.avatar, class: 'img-circle' %></div>
        <% else %>
          <div id="initials-wrapper" class="second-font" data-fullname="<%=@profile.fullname%>"></div>
          <%= javascript_pack_tag 'profile_header_initials.js' %>
        <%end%> 
        <div id="header-profile-fullname" class="primary-font fullname-padding">
          <%= @profile.fullname %>
        </div>
        <div class="vectordown-wrapper">
          <%= image_tag("Vectordown.svg", class: "vectordown-img") %>
        </div>
      </div>
      <div class="dropdown-content-wrapper">
        <div class="dropdown-content">
          <%= link_to destroy_user_session_path, method: :delete, class: "signout-link" do %>
            <div class="signout-text-wrapper">
              <h3 class="signout-text-content">Cerrar sesión</h3>
            </div>
          <% end %>
        </div> 
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/_admin_menu.html.erb
<div class="links-menu-wrapper">
  <% if controller_name == "profiles"%>
    <div class="highlight-section-link section-link primary-font">
      <%= link_to 'Perfil', edit_profile_path(id: @profile.id), class: 'highlight-text' %>
    </div>
  <% else %>
    <div class="section-link primary-font">
      <%= link_to 'Perfil', edit_profile_path(id: @profile.id) %>
    </div>
  <% end %>
  <% if controller_name == "publications"%>
    <div class="highlight-section-link section-link primary-font">
      <%= link_to 'Imágenes', publications_path, class: 'highlight-text' %>
    </div>
  <% else %>
    <div class="section-link primary-font">
      <%= link_to 'Imágenes', publications_path %>
    </div>
  <% end %> 
  <% if controller_name == "monetary_accounts"%>
    <div class="highlight-section-link section-link primary-font">
      <%= link_to 'Cuentas', monetary_accounts_path, class: 'highlight-text' %>
    </div>
  <% else %>
    <div class="section-link primary-font">
      <%= link_to 'Cuentas', monetary_accounts_path %>
    </div>
  <% end %> 
  <div class="section-link primary-font">
    <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'link-font-color' %>
  </div>   
</div>

app/views/layouts/_main_header.html.erb
<header class="header third-bkgrnd main-header">
  <%= link_to root_path do %>
    <div class="header-logo second-bkgrnd">
      <h1 class="logo-font second-font">A&C</h1> 
    </div>      
  <% end %>
  <% if current_page?(root_path) && !current_user %>
    <%= link_to new_user_session_path do %>
      <div class="login-container" >
        <h2 class="login-link primary-font">Login</h2>
      </div>         
    <% end %>
  <% end %>
</header>

app/views/layouts/_profile_header.html.erb
<header class="header third-bkgrnd profile-header">
  <%= link_to profile_path, class: "profile-link" do %>
    <% if @profile.avatar.present? %>
      <div class="profile-avatar"><%= image_tag @profile.avatar, class: 'img-circle' %></div>
    <% else %>
      <div id="initials-wrapper" class="second-font" data-fullname="<%=@profile.fullname%>"></div>
      <%= javascript_pack_tag 'profile_header_initials.js' %>
    <%end%>
    <div class="header-profile-data">
      <div id="header-profile-fullname" class="primary-font">
        <%= @profile.fullname %>
      </div>
      <div class="header-profile-occupation primary-font">
        <%= @profile.occupation %>
      </div>
    </div>
  <% end %>
  <%= link_to root_path do %>
    <div class="header-logo-container">
      <div class="header-logo second-bkgrnd">
        <h1 class="logo-font second-font ">A&C</h1> 
      </div>
    </div>
  <% end %>
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hugs And Coffee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'publish_profile.js' %>
    <%= javascript_pack_tag 'profile_menu.js' %>
    <%= javascript_pack_tag 'hide_flash_msg.js' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/monetary_accounts/_form.html.erb
<%= form_with model: @monetary_account do |f| %>
  <div class="account-form-wrapper">
    <div>
      <span class="primary-font publication-subtitle">Información de la cuenta</span>
      <p class="primary-font subtitle-description">Crea una cuenta donde las personas puedan agradecerte.</p>
    </div>
    <div class="money-acc-wrapper third-bkgrnd">
      <div class="alt-field">
        <%= f.label :entity, 'Entidad', class: "label primary-font" %>
        <%= f.text_field :entity, class: 'alt-field-field publ-field third-bkgrnd' %>
      </div>

      <div class="alt-field">
        <%= f.label :account_email, 'Email', class: "label primary-font" %>
        <%= f.text_field :account_email, class: 'alt-field-field publ-field third-bkgrnd' %>
      </div>

      <div class="alt-field">
        <%= f.label :account_number, 'Número de cuenta', class: "label primary-font" %>
        <%= f.text_field :account_number, class: 'alt-field-field publ-field third-bkgrnd' %>
      </div>

      <div class="alt-field">
        <%= f.label :identification, 'Identificación', class: "label primary-font" %>
        <%= f.text_field :identification, class: 'alt-field-field publ-field third-bkgrnd' %>
      </div>

      <div class="alt-field">
        <%= f.label :account_kind, 'Tipo de cuenta', class: "label primary-font" %>
        <%= f.text_field :account_kind, class: 'alt-field-field publ-field third-bkgrnd' %>
      </div>
    </div>
  </div>
  <div class="submit-btn-wrapper submit-btn-break profile-submit-wrapper">
    <%= f.submit "Guardar", class: "submit submit-2 primary-font second-bkgrnd" %>
  </div>
<% end %>

app/views/monetary_accounts/_form_edit.html.erb
<%= form_with model: @monetary_account do |f| %>
  <div class="account-form-wrapper">
    <div>
      <span class="primary-font publication-subtitle">Información de la cuenta</span>
      <p class="primary-font subtitle-description">Crea una cuenta donde las personas puedan agradecerte.</p>
    </div>
    <div class="money-acc-wrapper third-bkgrnd">
      <div class="alt-field">
        <%= f.label :entity, 'Entidad', class: "label primary-font" %>
        <%= f.text_field :entity, class: 'alt-field-field publ-field third-bkgrnd' %>
      </div>

      <div class="alt-field">
        <%= f.label :account_email, 'Email', class: "label primary-font" %>
        <%= f.text_field :account_email, class: 'alt-field-field publ-field third-bkgrnd' %>
      </div>

      <div class="alt-field">
        <%= f.label :account_number, 'Número de cuenta', class: "label primary-font" %>
        <%= f.text_field :account_number, class: 'alt-field-field publ-field third-bkgrnd' %>
      </div>

      <div class="alt-field">
        <%= f.label :identification, 'Identificación', class: "label primary-font" %>
        <%= f.text_field :identification, class: 'alt-field-field publ-field third-bkgrnd' %>
      </div>

      <div class="alt-field">
        <%= f.label :account_kind, 'Tipo de cuenta', class: "label primary-font" %>
        <%= f.text_field :account_kind, class: 'alt-field-field publ-field third-bkgrnd' %>
      </div>
    </div>
  </div>
  <div class="edit-publ-btns">
    <%= f.submit "Guardar", class: "submit submit-2 save-btn-text primary-font second-bkgrnd" %>

    <%= link_to monetary_account_path(@monetary_account), data: { method: :delete }, class: 'create-profile-link submit-2 third-bkgrnd delete-btn' do %>
      <h2 class="primary-font delete-btn-text">Eliminar</h2>
    <%end%>
  </div>
<% end %>

app/views/monetary_accounts/edit.html.erb
<div>
  <div id="profile-menu">
    <div class="profile-menu-header">
      <%= link_to @profile do %>
        <div class="header-logo second-bkgrnd">
          <h1 class="logo-font second-font ">A&C</h1> 
        </div>      
      <% end %>
      <%= image_tag("Vectorprofilemenu.svg", id: "vectorprofilemenu-img") %>
    </div>
    <%= render 'layouts/admin_menu' %>
  </div>
  <div id="profile-admin-dark">
    <div id="profile-form-main">
      <%= render 'layouts/admin_header' %>
      <div class="profile-form-desktop">
        <%= render 'layouts/admin-menu-desktop' %>
        <div class="account-form-container">
          <div class="publication-form-header">
            <div class="profile-form-title primary-font">Editar cuenta</div>
          </div>
          <%= render 'form_edit', object: @monetary_account %>       
        </div>
      </div>
    </div>
  </div>
</div>
 

app/views/monetary_accounts/index.html.erb
<div>
  <div id="profile-menu">
    <div class="profile-menu-header">
      <%= link_to @profile do %>
        <div class="header-logo second-bkgrnd">
          <h1 class="logo-font second-font ">A&C</h1> 
        </div>      
      <% end %>
      <%= image_tag("Vectorprofilemenu.svg", id: "vectorprofilemenu-img") %>
    </div>
    <%= render 'layouts/admin_menu' %>
  </div>
  <div id="profile-admin-dark">
    <div id="profile-form-main">
      <%= render 'layouts/admin_header' %>
      <div class="profile-form-desktop">
        <%= render 'layouts/admin-menu-desktop'%>
        <div class="account-list-container primary-bkgrnd">
          <div class="images-list-header">
            <% flash.each do |message_type, msg| %>
              <%= content_tag(:div, id: "msg-wrapper", class: "msg-wrapper #{message_type}") do %>
                <%= content_tag(:div, class: "vectormsg-wrapper") do %>
                  <%= image_tag("Vectormsg.svg", id: "vectormsgwrapper-img") %>                
                <% end %>
                <%= content_tag(:h6, msg, class: "primary-font") %>
              <% end %>
            <% end %>          
            <div class="profile-form-title primary-font">Listado de Cuentas</div>
            <div>
              <%= link_to new_monetary_account_path, class: "second-bkgrnd new-publ-link" do %>
                <h2 class="primary-font new-publ-link-text">Agregar</h2>
              <% end %>
            </div>
          </div>
          <div class="third-bkgrnd">
            <% @monetary_accounts.each do |monetary_account| %>
              <div class="acc-list-item">
                <div class="acc-items">
                  <div class="acc-entity primary-font">
                    <%= monetary_account.entity %>
                  </div>
                  <div class="acc-sublist">
                    <% if monetary_account.identification.present? %>
                      <div class="acc-data primary-font">
                        <%= monetary_account.identification %>
                      </div>
                    <% end %> 
                    <% if monetary_account.account_email.present? %>
                      <div  class="acc-data primary-font">
                        <%= monetary_account.account_email %>
                      </div>
                    <% end %>
                    <% if monetary_account.account_number.present? %>
                      <div  class="acc-data primary-font">
                        <%= monetary_account.account_number %>
                      </div>
                    <% end %>     
                    <% if monetary_account.account_kind.present? %>
                      <div  class="acc-data primary-font">
                        <%= monetary_account.account_kind %>
                      </div>
                    <% end %>  
                  </div>             
                </div>
                <div class="account-dropdown">
                  <div class="account-dropbtn">
                    <div class="three-dots-wrapper">
                      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
                      </svg>                
                    </div>           
                  </div>
                  <div class="dropdown-content-wrapper2">
                    <div class="dropdown-content-2">
                      <%= link_to edit_monetary_account_path(id: monetary_account.id), class: "signout-link" do %>
                        <div class="accsubmenu-text-wrapper">
                          <h3 class="accsubmenu-text-content">Editar</h3>
                        </div>
                      <% end %>
                      <%=  link_to monetary_account_path(id: monetary_account.id), data: { method: :delete }, class: "signout-link" do %>
                        <div class="accsubmenu-text-wrapper">
                          <h3 class="accsubmenu-text-content">Eliminar</h3>
                        </div>
                      <% end %>
                    </div> 
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
 

app/views/publications/_form_edit.html.erb
<%= form_with model: @publication do |f| %> 
  <div>
    <div class="publ-form-desktop">
      <div>
        <span class="primary-font publication-subtitle">Subtítulo</span>
        <p class="primary-font subtitle-description">Agrega un subtítulo que le otorgue vida a tu imagen.</p>
      </div>
      <div class="publ-form-subtitle third-bkgrnd">
        <%= f.label :subtitle, 'Subtítulo', class: "label primary-font" %>
        <%= f.text_field :subtitle, class: 'field-field publ-field third-bkgrnd' %>
      </div>
    </div>
    <div class="publ-form-desktop">
      <div class="img-form-label">
        <span class="primary-font publication-subtitle">Imagen</span>
        <p class="primary-font subtitle-description">Comparte imágenes que conecten con las personas y muestren a que te dedicas.</p>
      </div>
      <div class="dropify-customized">
        <%= f.file_field :image, class: 'dropify', id: "input-file-now" %>
      </div>
    </div>
  </div>
  <div class="edit-publ-btns">
    <%= f.submit "Guardar", class: "submit submit-2 save-btn-text primary-font second-bkgrnd" %>

    <%= link_to publication_path(@publication), data: { method: :delete }, class: 'create-profile-link submit-2 third-bkgrnd delete-btn' do %>
      <h2 class="primary-font delete-btn-text">Eliminar</h2>
    <%end%>
  </div>
<% end %>

app/views/publications/index.html.erb
<div>
  <div id="profile-menu">
    <div class="profile-menu-header">
      <%= link_to @profile do %>
        <div class="header-logo second-bkgrnd">
          <h1 class="logo-font second-font ">A&C</h1> 
        </div>      
      <% end %>
      <%= image_tag("Vectorprofilemenu.svg", id: "vectorprofilemenu-img") %>
    </div>
    <%= render 'layouts/admin_menu' %>
  </div>
  <div id="profile-admin-dark">
    <div id="profile-form-main">
      <%= render 'layouts/admin_header' %>
      <div class="profile-form-desktop">
        <%= render 'layouts/admin-menu-desktop' %>
        <div class="images-list-container primary-bkgrnd">
          <div class="images-list-header">
            <% flash.each do |message_type, msg| %>
              <%= content_tag(:div, id: "msg-wrapper", class: "msg-wrapper #{message_type}") do %>
                <%= content_tag(:div, class: "vectormsg-wrapper") do %>
                  <%= image_tag("Vectormsg.svg", id: "vectormsgwrapper-img") %>                
                <% end %>
                <%= content_tag(:h6, msg, class: "primary-font") %>
              <% end %>
            <% end %>          
            <div class="profile-form-title primary-font">Listado de Imágenes</div>
            <div>
              <%= link_to new_publication_path, class: "second-bkgrnd new-publ-link" do %>
                <h2 class="primary-font new-publ-link-text">Agregar</h2>
              <% end %>
            </div>
          </div>
          <% if @publications.any? %>
           <div class="image-list-wrapper third-bkgrnd">
            <% @publications.each do |publication| %>
              <%= link_to edit_publication_path(id: publication.id) do %>
                <%= image_tag publication.image, class: "publ-image-link" %>
              <% end %>
            <% end %>
            </div>         
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
 